client/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('client_site.urls')),
    path('celery-progress/', include('celery_progress.urls'))
]

client_site/urls.py
from django.urls import path

from . import views

app_name = 'client_site'
urlpatterns = [
    path('', views.index, name='index')
]

force_account_generator/force_account_generator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('celery-progress/', include('celery_progress.urls'))
]

force_account_generator/webapp/urls.py
from django.urls import path

from . import views

app_name = 'webapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('generate/', views.generate, name='generate'),
    path('packages/<uuid:task_id>', views.packages, name='packages'),
    path('about/', views.about, name='about'),
    path('demo/', views.demo, name='demo')
]

force_account_generator/webapp/models.py
import os
from django.db import models
from django.dispatch import receiver
from custom_storages import GeneratedStorage, UploadedStorage


class UploadedFile(models.Model):
    docfile = models.FileField(storage=UploadedStorage())
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.id} ({self.docfile.name})'


class ForceAccountPackage(models.Model):
    docfile = models.FileField(storage=GeneratedStorage())
    task_id = models.UUIDField(blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.id} ({self.task_id})'


@receiver(models.signals.post_delete, sender=UploadedFile)
def auto_delete_file(sender, instance, **kwargs):
    if instance.docfile:
        if os.path.isfile(instance.path):
            os.remove(instance.path)

force_account_generator/webapp/forms.py
from django import forms


class GenerateForceAccountForm(forms.Form):
    docfile = forms.FileField(required=True)
    daily_sheets = forms.BooleanField(initial=False, required=False)
    save_json = forms.BooleanField(initial=False, required=False)

force_account_generator/webapp/views.py
import os
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404
from .forms import GenerateForceAccountForm
from .tasks import generate_force_account
from .models import UploadedFile, ForceAccountPackage


def index(request):
    form = GenerateForceAccountForm()
    return render(request, 'webapp/index.html', {'form': form})


def generate(request):
    if request.method == 'POST':
        form = GenerateForceAccountForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_file = UploadedFile()
            uploaded_file.docfile.save(request.FILES['docfile'].name, request.FILES['docfile'])
            daily_sheets = form.cleaned_data['daily_sheets']
            result = generate_force_account.delay(uploaded_file.id, daily_sheets=daily_sheets)
            return JsonResponse({'task_id': result.task_id})
    response = JsonResponse({'error': 'Bad request'})
    response.status_code = 400
    return response


def packages(request, task_id):
    package = get_object_or_404(ForceAccountPackage, task_id=task_id)
    response = HttpResponse(package.docfile, content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename={package.docfile}'
    return response


def about(request):
    return render(request, 'webapp/about.html')


def demo(request):
    file_id = os.environ.get('DEMO_FILE_ID')
    print(file_id)
    result = generate_force_account.delay(file_id)
    return JsonResponse({'task_id': result.task_id})

force_account_generator/webapp/templates/webapp/about.html
{% extends 'webapp/index.html' %} {% load static %} {% block imports %}
<link rel="stylesheet" href="https://unpkg.com/tailwindcss@1.7.5/dist/base.css" />
<link rel="stylesheet" type="text/css" href="{% static 'webapp/styles.css' %}" />
<link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;700&display=swap" rel="stylesheet" />
{% endblock imports %} {% block content %}

<div class="background-container">
  <div class="background"></div>
</div>
<div class="container">
  <div class="navbar">
    <h1><a href="{% url 'webapp:index' %}">Force Account Generator</a></h1>
    <div class="nav-buttons">
      <a href="{% url 'webapp:index' %}" class="nav-item">
        <svg viewBox="0 0 24 20" fill="currentColor">
          <path
            fill-rule="evenodd"
            d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z"
            clip-rule="evenodd"
          ></path>
        </svg>
        <span>Back to the generator</span>
      </a>
    </div>
  </div>

  <div class="about-article">
    <h2>Tired of filling out PDF forms?</h2>
    <p>
      The Force Account Generator was born out of a desire to quickly fill in proprietary PDF forms with Excel data. As
      it stands, the PennDOT force account package PDF is cumbersome, requires duplicate effort, and is inadequate for
      large datasets. Furthermore, filling in individual form fields on a PDF is tiresome and prone to error. The Force
      Account Generator fixes all of that. It allows users to easily enter their data into Excel and generate a valid
      PDF form for submission. It saves time and reduces human error.
    </p>
    <h2>How to use it</h2>
    <p>
      First, <a href="{% static 'webapp/template.xlsx' %}">download the Excel template</a>. The template should be
      familiar to anyone who has created a PennDOT force account before. Simply fill in the required information on each
      tab and save the file on your computer. Come back here to the generator, click the checkbox if you'd like to
      generate daily sign-off sheets, and drop your Excel file in the file dropzone on the main page. We will do the
      rest of the work!
    </p>
    <h2>How it's built</h2>
    <p>
      The generator originated as a Python script with a
      <a href="https://docs.python.org/3/library/tkinter.html" target="_blank">Tkinter</a> interface, but evolved to the
      <a href="https://www.djangoproject.com/" target="_blank">Django</a>-based application you see today. The Django
      backend utilizes a pool of <a href="https://docs.celeryproject.org/en/stable/">Celery</a> workers to
      asynchronously process the Excel workbook and build the PDF file. The status of the process is continuously
      queried by the frontend via an API endpoint to allow realtime updates.
    </p>
    <p>
      The Excel file is read into a large data structure using the
      <a href="https://openpyxl.readthedocs.io/en/stable/" target="_blank">openpyxl</a> library. This large data
      structure is then handed off to the PDF generator portion of the program, which performs intermediary
      calculations, formats the output, and paginates the data to fit the structure of the PennDOT force account forms.
      Blank template PDF form pages are then populated with the appropriate data using the
      <a href="https://pythonhosted.org/PyPDF2/">PyPDF2</a> library. The pages are merged and the PDF is saved and
      served to the user. All static, user-uploaded, and generated files are remotely stored in an AWS S3 bucket.
    </p>
    <p>
      The frontend uses a combination of the Django templating engine for initial rendering and routing along with
      <a href="https://github.com/alpinejs/alpine" target="_blank">AlpineJS</a> and
      <a href="https://www.dropzonejs.com/" target="_blank">DropzoneJS</a>
      for the reactive components of the design.
    </p>
  </div>
</div>

{% endblock content %}

force_account_generator/webapp/templates/webapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block imports %}
    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@1.7.5/dist/base.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'webapp/styles.min.css' %}" />
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;700&display=swap" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    {% endblock imports %}
    <title>Force Account Generator</title>
  </head>
  <body
    x-data="appData"
    @processingupload.window="setUploading($event.detail)"
    @uploadprogress.window="bytesSent = $event.detail.bytesSent"
    @uploadsuccess.window="uploading = false; taskId = $event.detail.taskId"
    @error.window="error = $event.detail.error"
    @resetform.window="reset()"
    @setstage.window="setStage($event.detail.stage)"
    @pdfprogress.window="currentPage = $event.detail.current; totalPages = $event.detail.total"
  >
    {% block content %}
    <div class="background-container">
      <div class="background"></div>
    </div>
    <div class="container">
      <div class="navbar">
        <h1><a href="{% url 'webapp:index' %}">Force Account Generator</a></h1>
        <div class="nav-buttons">
          <div class="demo-button nav-item" @click="runDemo()">
            <span>Demo it!</span>
          </div>
          <a href="{% url 'webapp:about' %}" class="nav-item">
            <svg viewBox="0 0 20 20" fill="currentColor">
              <path
                fill-rule="evenodd"
                d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z"
                clip-rule="evenodd"
              ></path>
            </svg>
            <span>About</span>
          </a>
        </div>
      </div>
      <div class="heading">
        <h2>
          Generate PennDOT force accounts,<br />
          <strong>without the pain.</strong>
        </h2>
        <span>Create valid PennDOT PDF Force Account packages, from a simple Excel spreadsheet.</span>
        <div class="heading-actions">
          <a href="{% static 'webapp/template.xlsx' %}" class="button button-primary button-icon download">
            <svg viewBox="0 0 20 20" fill="currentColor">
              <path
                fill-rule="evenodd"
                d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z"
                clip-rule="evenodd"
              ></path>
            </svg>
            Download the Excel template
          </a>
          <a
            href="https://github.com/bk7987/force-account-generator"
            class="ml-3 button button-icon external-link"
            target="_blank"
          >
            <span>Source code</span>
            <svg viewBox="0 0 20 20" fill="currentColor" stroke-width="1">
              <path
                d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z"
              ></path>
              <path d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z"></path>
            </svg>
          </a>
        </div>
      </div>

      <div class="form-options" x-show="!fileAdded">
        <input type="checkbox" name="daily_sheets" form="mydropzone" id="daily_sheets" />
        <label for="daily_sheets">Generate daily sign-off sheets</label>
      </div>
      <form
        action="{% url 'webapp:generate' %}"
        method="post"
        enctype="multipart/form-data"
        class="mydropzone"
        id="mydropzone"
        :style="'border-color: ' + (error ? '#e53e3e' : '#90cdf4')"
        x-show="!fileAdded"
      >
        {% csrf_token %}
        <div class="dz-message"></div>
        <div class="dropzone-message" :style="'color: ' + error ? 'red' : 'inherit'">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="document-add" fill="currentColor">
            <path
              d="M23 1.5q.41 0 .7.3.3.29.3.7v19q0 .41-.3.7-.29.3-.7.3H7q-.41 0-.7-.3-.3-.29-.3-.7V18H1q-.41 0-.7-.3-.3-.29-.3-.7V7q0-.41.3-.7Q.58 6 1 6h5V2.5q0-.41.3-.7.29-.3.7-.3zM6 13.28l1.42 2.66h2.14l-2.38-3.87 2.34-3.8H7.46l-1.3 2.4-.05.08-.04.09-.64-1.28-.66-1.29H2.59l2.27 3.82-2.48 3.85h2.16zM14.25 21v-3H7.5v3zm0-4.5v-3.75H12v3.75zm0-5.25V7.5H12v3.75zm0-5.25V3H7.5v3zm8.25 15v-3h-6.75v3zm0-4.5v-3.75h-6.75v3.75zm0-5.25V7.5h-6.75v3.75zm0-5.25V3h-6.75v3z"
            />
          </svg>
          <span>Drop your Excel file here</span>
        </div>
      </form>

      <div id="upload-status"></div>
      {% include 'webapp/partials/dropzone_template.html' %} {% include 'webapp/partials/pdf_progress.html' %}

      <div class="error-banner" x-show.transition.in.opacity.duration.1000ms="error">
        <div class="error-banner-details">
          <svg fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
            ></path>
          </svg>
          <span x-text="error"></span>
        </div>
        <div class="error-banner-close" @click="$dispatch('resetform')">
          <svg fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
          </svg>
        </div>
      </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.2/min/dropzone.min.js"></script>
    <script src="{% static 'celery_progress/celery_progress.js' %}"></script>
    <script src="{% static 'webapp/main.min.js' %}"></script>

    {% endblock content %}
  </body>
</html>

force_account_generator/webapp/templates/webapp/partials/dropzone_template.html
<div style="width: 100%;">
  <div id="dropzone-template" style="width: 100%;" x-show="fileAdded">


    <div 
      class="dropzone-template-wrapper" 
    >
      <span 
        x-text="uploading ? 'Uploading' : 'Uploaded'"
        :style="'color: ' + (uploading ? '#3182ce' : '#38a169')"
      >
      </span>

      <div class="progress-wrapper">
        <div class="progress-info">
          <div data-dz-name class="dropzone-name"></div>
          <div class="progress-info-size">
            <div class="progress-completed-size" x-text="transferredSize"></div>
            <span>/</span>
            <div class="progress-total-size" x-text="fileSize + ' ' + fileSizeUnit"></div>
          </div>
        </div>

        <div class="progress-bar">
          <div :style="'width: ' + transferredPercent + '; background-color: ' + (uploading ? '#3182ce' : '#68d391')"></div>
        </div>
      </div>

    </div>



  </div>
</div>

force_account_generator/webapp/templates/webapp/partials/pdf_progress.html
<div class="pdf-progress">
  <!-- STAGE 1 -->
  <div
    :class="{ 'active': stage === 1, 'completed': stage > 1 }"
    id="stage-1"
    x-show.transition.in.opacity.duration.300ms="stage >= 1"
  >
    <div class="step-icon">
      <svg viewBox="0 0 20 20" fill="currentColor" class="success-icon">
        <path
          fill-rule="evenodd"
          d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
          clip-rule="evenodd"
        ></path>
      </svg>
    </div>
    <div class="step-content" x-text="'Loading data from Excel file'"></div>
  </div>

  <!-- STAGE 2 -->
  <div
    :class="{ 'active': stage === 2, 'completed': stage > 2 }"
    id="stage-2"
    x-show.transition.in.opacity.duration.300ms="stage >= 1"
  >
    <div class="step-icon">
      <svg viewBox="0 0 20 20" fill="currentColor" class="success-icon">
        <path
          fill-rule="evenodd"
          d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
          clip-rule="evenodd"
        ></path>
      </svg>
    </div>
    <div class="step-content">
      <div class="progress-wrapper">
        <div class="progress-info">
          <span>Generating PDF pages</span>
          <div class="progress-info-size" x-show="stage >= 2">
            <div class="progress-completed-size" x-text="currentPage"></div>
            <span>/</span>
            <div class="progress-total-size" x-text="totalPages + ' pages'"></div>
          </div>
        </div>

        <div class="progress-bar" x-show="stage >= 2">
          <div
            :style="'width: ' + (currentPage/totalPages) * 100 + '%; background-color: ' + (stage >= 3 ? '#e2e8f0' : '#3182ce')"
          ></div>
        </div>
      </div>
    </div>
  </div>

  <!-- STAGE 3 -->
  <div
    :class="{ 'active': stage === 3, 'completed': stage > 3 }"
    id="stage-3"
    x-show.transition.in.opacity.duration.300ms="stage >= 1"
  >
    <div class="step-icon">
      <svg viewBox="0 0 20 20" fill="currentColor" class="success-icon">
        <path
          fill-rule="evenodd"
          d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
          clip-rule="evenodd"
        ></path>
      </svg>
    </div>
    <div class="step-content" x-text="'Saving PDF to file'"></div>
  </div>
</div>

<!-- PDF READY -->
<div class="completed-popup" x-show.transition.in.opacity.duration.1000ms="stage >= 4">
  <div class="refresh-button">
    <div @click="reset()">
      <svg fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
        ></path>
      </svg>
    </div>
  </div>
  <div class="pdf-ready">
    <span>Your PDF is ready!</span>
    <a class="button button-primary-inverse button-icon" :href="'packages/' + taskId">
      <svg viewBox="0 0 20 20" fill="currentColor">
        <path
          fill-rule="evenodd"
          d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z"
          clip-rule="evenodd"
        ></path>
      </svg>
      <span>Download PDF</span>
    </a>
  </div>
</div>